/* ====================================================================
   MUSIC ARCADE — the reading list behind the creativity workshops
   --------------------------------------------------------------------
   One catalogue, two pages:
     reading-list.html  the public shelf (titles, authors, where to read)
     reading.html       William's private tracker (statuses + notes, teacher-only)
   TO ADD A BOOK: one row below. `id` must never change — it is the key the
   tracker stores statuses and notes against.
     phase  1 mine for exercises · 2 embodied traditions · 3 way traditions
            4 somatics · 5 aesthetics & philosophy · 6 research · 7 format studies
     doi    papers: the link goes straight to doi.org   oa: true if it's open access
     pd     public-domain books: the link goes to the full text on the Internet Archive
     note   William's working note — shown only in the private tracker
   ==================================================================== */
(function () {
  'use strict';
  window.READING_PHASES = { 1:"Mine for exercises", 2:"Embodied traditions", 3:"Way traditions", 4:"Somatics", 5:"Aesthetics & philosophy", 6:"Research literature", 7:"Format studies" };
  window.READING_STRANDS = { Listening:"#2438C8", Improvisation:"#F05B3C", Embodied:"#1E9E6E", Meditation:"#7A5FD0", Somatics:"#E8A013", Aesthetics:"#0E8C96", Research:"#6B6456", Format:"#FF4E86" };

  window.READING_CATALOG = [
  { id:"sonic-meditations", title:"Sonic Meditations", author:"Pauline Oliveros", year:"1974", phase:1, strand:"Listening", connects:["Music","Meditation","Somatics"], note:"Twenty-five text scores for group listening and sounding. Several work with a room of teenagers as written. The densest seam of stealable exercises on the whole list." },
  { id:"deep-listening", title:"Deep Listening: A Composer's Sound Practice", author:"Pauline Oliveros", year:"2005", phase:1, strand:"Listening", connects:["Music","Meditation","Somatics"], note:"The fuller practice behind the scores — listening as meditation, body work included. Read after Sonic Meditations. Note: Deep Listening is essentially open-monitoring practice aimed at sound." },
  { id:"listening-book", title:"The Listening Book", author:"W.A. Mathieu", year:"1991", phase:1, strand:"Listening", connects:["Music","Meditation","Spirituality"], note:"Two-page chapters, each nearly an exercise. Sufi lineage under the surface but never announced — a model for carrying the spiritual layer without naming it in class." },
  { id:"sound-education", title:"A Sound Education: 100 Exercises", author:"R. Murray Schafer", year:"1992", phase:1, strand:"Listening", connects:["Music","Play"], note:"A hundred listening exercises written for actual school classrooms. Your closest precedent — expect the highest steal-rate per page." },
  { id:"free-play", title:"Free Play: Improvisation in Life and Art", author:"Stephen Nachmanovitch", year:"1990", phase:1, strand:"Improvisation", connects:["Music","Play","Spirituality"], note:"Improvisation as a way of being. More Say than Steal — this is where the workshops get their spine." },
  { id:"impro", title:"Impro: Improvisation and the Theatre", author:"Keith Johnstone", year:"1979", phase:1, strand:"Improvisation", connects:["Play","Movement","Word"], note:"Theatre games built to disarm self-censorship in groups. Translate them from speech and gesture into sound and you have a workshop." },
  { id:"chernoff", title:"African Rhythm and African Sensibility", author:"John Miller Chernoff", year:"1979", phase:2, strand:"Embodied", connects:["Music","Movement","Spirituality"], note:"A drummer's apprenticeship among the Dagomba in Ghana. Competence is participatory — you understand by joining — and the gaps in the drumming exist for the dancers." },
  { id:"agawu", title:"The African Imagination in Music", author:"Kofi Agawu", year:"2016", phase:2, strand:"Embodied", connects:["Music","Movement","Aesthetics"], note:"The corrective to romanticising African rhythm as one monolithic thing. Read alongside Chernoff — keeps the framing honest." },
  { id:"musicking", title:"Musicking", author:"Christopher Small", year:"1998", phase:2, strand:"Embodied", connects:["Music","Movement","Aesthetics"], note:"Music as verb, not noun — something people do together, not an object. This one word may end up in your workshop copy." },
  { id:"turino", title:"Music as Social Life", author:"Thomas Turino", year:"2008", phase:2, strand:"Embodied", connects:["Music","Movement"], note:"Participatory vs. presentational music. Your workshops are participatory practice inside a school system built for presentational music — Turino gives you the words to say so." },
  { id:"carson", title:"Last Night's Fun", author:"Ciaran Carson", year:"1996", phase:2, strand:"Embodied", connects:["Music","Movement","Word"], note:"The Irish session as lived, embodied practice — tunes, drink, talk, time. Your own tradition making the same point the Ghanaian material makes, and a joy to read." },
  { id:"floyd", title:"The Power of Black Music", author:"Samuel Floyd", year:"1995", phase:2, strand:"Embodied", optional:true, connects:["Music","Movement","Spirituality"], note:"The ring shout and its long echo through African-American music — movement, spirit and sound staying fused in a Western context." },
  { id:"wooten", title:"The Music Lesson", author:"Victor Wooten", year:"2006", phase:2, strand:"Embodied", optional:true, connects:["Music","Spirituality","Word"], note:"Music-as-spirituality written as a novel by a working bassist. Loose, but it speaks teenagers' language and is unashamedly embodied." },
  { id:"suzuki", title:"Zen Mind, Beginner's Mind", author:"Shunryu Suzuki", year:"1970", phase:3, strand:"Meditation", connects:["Meditation","Spirituality"], note:"In the beginner's mind there are many possibilities; in the expert's, few. The Gradus nursery-rhyme framing in its original habitat." },
  { id:"werner", title:"Effortless Mastery", author:"Kenny Werner", year:"1996", phase:3, strand:"Meditation", connects:["Music","Meditation"], note:"Meditation at the instrument, for players frozen by self-judgement. The most classroom-adjacent of the way traditions." },
  { id:"cage", title:"Silence", author:"John Cage", year:"1961", phase:3, strand:"Meditation", connects:["Music","Meditation","Word","Aesthetics"], note:"Zen arriving in Western aesthetics of listening. Dip in — the lectures matter more than cover-to-cover reading." },
  { id:"inayat-khan", title:"The Mysticism of Sound and Music", author:"Hazrat Inayat Khan", year:"1923", pd:true, phase:3, strand:"Meditation", connects:["Music","Meditation","Spirituality"], note:"The Sufi teaching Mathieu descends from — sound itself as spiritual path. Research layer, not classroom language." },
  { id:"herrigel", title:"Zen in the Art of Archery", author:"Eugen Herrigel", year:"1948", phase:3, strand:"Meditation", connects:["Meditation","Spirituality","Movement"], note:"The famous geido entry point the whole Dojo metaphor rests on. Caveat: scholars have shown Herrigel partly invented the Zen content — useful myth, held lightly." },
  { id:"dalcroze", title:"Rhythm, Music and Education", author:"Émile Jaques-Dalcroze", year:"1921", pd:true, phase:4, strand:"Somatics", connects:["Music","Movement","Somatics"], note:"The European tradition that systematised music-through-the-moving-body. Secondary guides to Eurhythmics practice may be more usable than the original." },
  { id:"feldenkrais", title:"Awareness Through Movement", author:"Moshé Feldenkrais", year:"1972", phase:4, strand:"Somatics", connects:["Somatics","Movement","Meditation"], note:"Lessons in attention through tiny movement. Mine for warm-up shapes." },
  { id:"alcantara", title:"Indirect Procedures", author:"Pedro de Alcantara", year:"1997", phase:4, strand:"Somatics", connects:["Music","Somatics"], note:"Alexander Technique written specifically for musicians." },
  { id:"bmc", title:"Sensing, Feeling, and Action", author:"Bonnie Bainbridge Cohen", year:"1993", phase:4, strand:"Somatics", optional:true, connects:["Somatics","Movement"], note:"Body-Mind Centering. Dense — likely better mined through Aneta and the Opacity vocabulary than through the page." },
  { id:"dewey", title:"Art as Experience", author:"John Dewey", year:"1934", phase:5, strand:"Aesthetics", connects:["Aesthetics","Visual art","Play"], note:"Art as ordinary experience intensified. The philosophical spine of the whole project." },
  { id:"schiller", title:"On the Aesthetic Education of Man", author:"Friedrich Schiller", year:"1795", pd:true, phase:5, strand:"Aesthetics", connects:["Aesthetics","Play"], note:"Play as the fullest expression of being human. The arcade's oldest ancestor — read a good introduction first, the letters are heavy going." },
  { id:"greene", title:"Releasing the Imagination", author:"Maxine Greene", year:"1995", phase:5, strand:"Aesthetics", connects:["Aesthetics","Word","Visual art"], note:"Aesthetic education argued for inside real school systems. Ammunition for principals and parents." },
  { id:"flow", title:"Flow", author:"Mihaly Csikszentmihalyi", year:"1990", phase:5, strand:"Aesthetics", connects:["Play","Aesthetics"], note:"The secular, research-backed cousin of the way traditions. The vocabulary schools already trust." },
  { id:"colzato", title:"Meditate to Create", author:"Colzato, Ozturk & Hommel · Frontiers in Psychology", year:"2012", doi:"10.3389/fpsyg.2012.00116", oa:true, phase:6, strand:"Research", connects:["Meditation"], note:"Open-monitoring meditation boosts divergent thinking; focused attention doesn't much. Caveat: lead author later found guilty of research misconduct and a related paper was retracted — treat as an idea-source, cite Lebuda instead. Open access on Frontiers." },
  { id:"lebuda", title:"Mindfulness & Creativity Meta-Analysis", author:"Lebuda, Zabelina & Karwowski", year:"2016", doi:"10.1016/j.paid.2015.09.040", phase:6, strand:"Research", connects:["Meditation"], note:"Small-to-moderate positive link between mindfulness and creativity across the literature. Your citable anchor for the whole strand." },
  { id:"limb", title:"Jazz Improvisation fMRI Study", author:"Limb & Braun · PLoS ONE", year:"2008", doi:"10.1371/journal.pone.0001679", oa:true, phase:6, strand:"Research", connects:["Music"], note:"Self-monitoring prefrontal cortex goes quiet while jazz musicians improvise in the scanner. Six subjects — evocative folklore with citations, and Limb's TED talk is a ready-made explainer for parents." },
  { id:"berkowitz", title:"The Improvising Mind", author:"Aaron Berkowitz", year:"2010", phase:6, strand:"Research", connects:["Music"], note:"Cognitive science of learned improvisation — vocabulary, chunks, recombination. Academic support for the Barry Harris block approach." },
  { id:"phillips-silver", title:"Feeling the Beat", author:"Phillips-Silver & Trainor · Science", year:"2005", doi:"10.1126/science.1110922", phase:6, strand:"Research", connects:["Music","Movement"], note:"Infants bounced in duple or triple time afterwards hear an ambiguous rhythm as the meter they were moved in. The ngoma insight as a two-page experiment. Adult follow-up in 2007." },
  { id:"leman", title:"Embodied Music Cognition", author:"Marc Leman", year:"2008", phase:6, strand:"Research", connects:["Music","Movement","Somatics"], note:"The systematic case that musical meaning runs through the body. Dense — skim for the framework." },
  { id:"varela", title:"The Embodied Mind", author:"Varela, Thompson & Rosch", year:"1991", phase:6, strand:"Research", connects:["Meditation","Somatics"], note:"Cognitive science meets Buddhist meditation practice. The academic bridge between the meditation and somatics shelves." },
  { id:"kirschner", title:"Joint Music Making & Prosocial Behavior", author:"Kirschner & Tomasello", year:"2010", doi:"10.1016/j.evolhumbehav.2010.04.004", phase:6, strand:"Research", connects:["Music","Movement","Play"], note:"Joint music-making increased spontaneous helping and cooperation in four-year-olds. Probably your single most school-pitchable citation." },
  { id:"wiltermuth", title:"Synchrony and Cooperation", author:"Wiltermuth & Heath · Psych. Science", year:"2009", doi:"10.1111/j.1467-9280.2008.02253.x", phase:6, strand:"Research", connects:["Movement","Music"], note:"Moving in time together — even just marching or singing — measurably increases cooperation afterwards." },
  { id:"sawyer", title:"Explaining Creativity", author:"Keith Sawyer", year:"2012", phase:6, strand:"Research", connects:["Music","Play"], note:"The best single gateway into creativity research, by a jazz pianist who studies group improvisation. If you read one academic book on this list, this is it. Group Genius is the popular companion." },
  { id:"four-c", title:"The Four C Model of Creativity", author:"Beghetto & Kaufman", year:"2009", doi:"10.1037/a0013688", phase:6, strand:"Research", connects:["Play","Aesthetics"], note:"mini-c to little-c to Pro-c to Big-C. A defensible answer to you-can't-teach-creativity: classrooms are the natural home of mini-c and little-c." },
  { id:"silvia-everyday", title:"Everyday Creativity in Daily Life: An Experience-Sampling Study of “Little c” Creativity", author:"Silvia, Beaty, Nusbaum, Eddington, Levin-Aspenson & Kwapil · Psychology of Aesthetics, Creativity, and the Arts", year:"2014", phase:6, strand:"Research", connects:["Play","Aesthetics"], doi:"10.1037/a0035722", note:"Seventy-nine young adults beeped through a week of ordinary days: creative activity turned up in roughly a fifth of the moments sampled, and people reported feeling happier and more active while doing it. Openness to experience predicted who did more. The ground-level evidence behind the Four C paper’s little-c — creativity as something that happens on a Tuesday, not in a studio." },
  { id:"amabile", title:"Creativity in Context", author:"Teresa Amabile", year:"1996", phase:6, strand:"Research", connects:["Play"], note:"Intrinsic motivation as creativity's engine — and evidence that surveillance and evaluation suppress it. Directly relevant to how, and whether, you assess anything in a workshop." },
  { id:"green", title:"Music, Informal Learning and the School", author:"Lucy Green", year:"2008", phase:6, strand:"Research", connects:["Music","Play"], note:"How popular musicians actually learn, brought into classrooms and researched — the Musical Futures programme. The closest thing to peer review of your whole teaching instinct." },
  { id:"myriad", title:"The MYRIAD Trial", author:"Kuyken et al. · Evidence-Based Mental Health", year:"2022", doi:"10.1136/ebmental-2021-300396", oa:true, phase:6, strand:"Research", connects:["Meditation"], note:"Largest RCT of universal school mindfulness (~28,000 UK pupils): no wellbeing benefit over normal teaching, largely because teenagers didn't practise. Two lessons — never sell the workshops as a wellbeing intervention, and design practices they actually want to repeat. Also the most trustworthy study here, precisely because it is big, pre-registered and null." },
  { id:"cameron", title:"The Artist's Way", author:"Julia Cameron", year:"1992", phase:7, strand:"Format", connects:["Spirituality","Word","Visual art"], note:"A 12-week structure with daily and weekly practices. Study the scaffolding; take or leave the content." },
  { id:"barry", title:"Syllabus", author:"Lynda Barry", year:"2014", phase:7, strand:"Format", connects:["Visual art","Word","Play"], note:"An actual creativity class published as a notebook. The closest thing to a Dojo course on paper." },
  { id:"rubin", title:"The Creative Act", author:"Rick Rubin", year:"2023", phase:7, strand:"Format", connects:["Spirituality","Aesthetics","Word"], note:"Fragment-sized chapters. A model for tone if the workshops ever become written material." },
  ];

  /* Where to actually read it. Papers go to their DOI (the open-access ones load in
     full); public-domain books go to the full text on the Internet Archive; everything
     else goes to Open Library, which shows a borrow/read option where one exists. */
  window.readingSource = function (s) {
    var surname = s.author.split(/[·,&]/)[0].trim().split(' ').pop();
    var q = encodeURIComponent(s.title + ' ' + surname);
    if (s.doi) return { href: 'https://doi.org/' + s.doi, label: s.oa ? 'Read the paper — open access' : 'Read the paper (DOI)', note: 'doi.org/' + s.doi, kind: 'paper' };
    if (s.pd)  return { href: 'https://archive.org/search?query=' + q + '&sin=TXT', label: 'Read the full text — public domain', note: 'Internet Archive', kind: 'pd' };
    return { href: 'https://openlibrary.org/search?q=' + q, label: 'Find a copy to read', note: 'Open Library — borrow where available', kind: 'book' };
  };
})();
